### ISSUE TITLE
php7.1下编译出错

### ISSUE THREAD

**Issue by yyz26371945** [swoole/swoole_serialize#1]
你好，最近在微博看见你的这个项目，今天下载下来想试试，但是在php7.1下编译出错
/bin/sh /home/yyz/thirdparty/tools/swoole_serialize-master/libtool --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/home/yyz/thirdparty/tools/swoole_serialize-master -DPHP_ATOM_INC -I/home/yyz/thirdparty/tools/swoole_serialize-master/include -I/home/yyz/thirdparty/tools/swoole_serialize-master/main -I/home/yyz/thirdparty/tools/swoole_serialize-master -I/home/yyz/thirdparty/php-7.1.0/include/php -I/home/yyz/thirdparty/php-7.1.0/include/php/main -I/home/yyz/thirdparty/php-7.1.0/include/php/TSRM -I/home/yyz/thirdparty/php-7.1.0/include/php/Zend -I/home/yyz/thirdparty/php-7.1.0/include/php/ext -I/home/yyz/thirdparty/php-7.1.0/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /home/yyz/thirdparty/tools/swoole_serialize-master/swoole_serialize.c -o swoole_serialize.lo 
 cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/home/yyz/thirdparty/tools/swoole_serialize-master -DPHP_ATOM_INC -I/home/yyz/thirdparty/tools/swoole_serialize-master/include -I/home/yyz/thirdparty/tools/swoole_serialize-master/main -I/home/yyz/thirdparty/tools/swoole_serialize-master -I/home/yyz/thirdparty/php-7.1.0/include/php -I/home/yyz/thirdparty/php-7.1.0/include/php/main -I/home/yyz/thirdparty/php-7.1.0/include/php/TSRM -I/home/yyz/thirdparty/php-7.1.0/include/php/Zend -I/home/yyz/thirdparty/php-7.1.0/include/php/ext -I/home/yyz/thirdparty/php-7.1.0/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /home/yyz/thirdparty/tools/swoole_serialize-master/swoole_serialize.c  -fPIC -DPIC -o .libs/swoole_serialize.o
/home/yyz/thirdparty/tools/swoole_serialize-master/swoole_serialize.c: In function 'swoole_unserialize_object':
/home/yyz/thirdparty/tools/swoole_serialize-master/swoole_serialize.c:468:12: error: 'zend_fcall_info' has no member named 'function_table'
         fci.function_table = &ce->function_table;
            ^
/home/yyz/thirdparty/tools/swoole_serialize-master/swoole_serialize.c:470:12: error: 'zend_fcall_info' has no member named 'symbol_table'
         fci.symbol_table = NULL;
            ^
In file included from /home/yyz/thirdparty/php-7.1.0/include/php/Zend/zend_globals.h:28:0,
                 from /home/yyz/thirdparty/php-7.1.0/include/php/Zend/zend_compile.h:688,
                 from /home/yyz/thirdparty/php-7.1.0/include/php/Zend/zend_modules.h:26,
                 from /home/yyz/thirdparty/php-7.1.0/include/php/Zend/zend_API.h:27,
                 from /home/yyz/thirdparty/php-7.1.0/include/php/main/php.h:39,
                 from /home/yyz/thirdparty/tools/swoole_serialize-master/swoole_serialize.c:25:
/home/yyz/thirdparty/php-7.1.0/include/php/Zend/zend_globals_macros.h:46:33: error: 'zend_executor_globals' has no member named 'scope'
 # define EG(v) (executor_globals.v)
                                 ^
/home/yyz/thirdparty/tools/swoole_serialize-master/swoole_serialize.c:480:29: note: in expansion of macro 'EG'
         fcc.calling_scope = EG(scope);
                             ^
make: *** [swoole_serialize.lo] Error 1

**Comment by GXhua** [comment]
请再试下

**Comment by GXhua** [comment]
我 改了下 代码 有可能php7.1的结构变了

**Comment by yyz26371945** [comment]
试了一下，还是有点问题
/bin/sh /home/yyz/thirdparty/tools/swoole_serialize-master/libtool --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/home/yyz/thirdparty/tools/swoole_serialize-master -DPHP_ATOM_INC -I/home/yyz/thirdparty/tools/swoole_serialize-master/include -I/home/yyz/thirdparty/tools/swoole_serialize-master/main -I/home/yyz/thirdparty/tools/swoole_serialize-master -I/home/yyz/thirdparty/php-7.1.0/include/php -I/home/yyz/thirdparty/php-7.1.0/include/php/main -I/home/yyz/thirdparty/php-7.1.0/include/php/TSRM -I/home/yyz/thirdparty/php-7.1.0/include/php/Zend -I/home/yyz/thirdparty/php-7.1.0/include/php/ext -I/home/yyz/thirdparty/php-7.1.0/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /home/yyz/thirdparty/tools/swoole_serialize-master/swoole_serialize.c -o swoole_serialize.lo 
mkdir .libs
 cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/home/yyz/thirdparty/tools/swoole_serialize-master -DPHP_ATOM_INC -I/home/yyz/thirdparty/tools/swoole_serialize-master/include -I/home/yyz/thirdparty/tools/swoole_serialize-master/main -I/home/yyz/thirdparty/tools/swoole_serialize-master -I/home/yyz/thirdparty/php-7.1.0/include/php -I/home/yyz/thirdparty/php-7.1.0/include/php/main -I/home/yyz/thirdparty/php-7.1.0/include/php/TSRM -I/home/yyz/thirdparty/php-7.1.0/include/php/Zend -I/home/yyz/thirdparty/php-7.1.0/include/php/ext -I/home/yyz/thirdparty/php-7.1.0/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /home/yyz/thirdparty/tools/swoole_serialize-master/swoole_serialize.c  -fPIC -DPIC -o .libs/swoole_serialize.o
/home/yyz/thirdparty/tools/swoole_serialize-master/swoole_serialize.c: In function 'swoole_string_new':
/home/yyz/thirdparty/tools/swoole_serialize-master/swoole_serialize.c:44:5: error: too few arguments to function 'memset'
     memset(str->buffer, total);
     ^
make: *** [swoole_serialize.lo] Error 1

**Comment by GXhua** [comment]
请再试

**Comment by yyz26371945** [comment]
已经可以了，非常感谢及时的回复
