### ISSUE TITLE
希望把序列化之后的大小能优化一下

### ISSUE THREAD

**Issue by yyz26371945** [swoole/swoole_serialize#2]
我们线上用的是hprose的pecl扩展，我刚刚测试了下最新的，确实很快，序列化和反序列时间基本是hprose的一半左右，但是唯一不太好的就是序列化之后的长度是hprose的接近3倍，希望优化一下哈~:)

**Comment by GXhua** [comment]
你好 请再测试下，现在大小是原生serialize的一半，是json的80%  和msgpack相当，同时性能是2-3倍

**Comment by yyz26371945** [comment]
嗯，感谢优化~刚刚测试了一下，有一定的减小，但是还是比较大，我测试的这部分数据是以object和array为主
下图是没优化之前的大小
![image](https://cloud.githubusercontent.com/assets/20291334/22050817/0f26f9fa-dd79-11e6-9c79-3761ca34c2da.png)
下图是优化之后的大小
![image](https://cloud.githubusercontent.com/assets/20291334/22050821/1a00db66-dd79-11e6-8224-b06631fbc15d.png)

**Comment by GXhua** [comment]
请把测试的数据发给我下

**Comment by GXhua** [comment]
393323503  加我qq吧

**Comment by yyz26371945** [comment]
你加我吧，340427874，你的那个需要验证手机号哈

**Comment by GXhua** [comment]
请再试下 现在尺寸是最小的了  所有的序列化算法里面
